// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxYN6svk13Y8ljs1eZY56PVdg52CPjerU',
    appId: '1:1028683149003:android:3c0502a97af302f40bb54e',
    messagingSenderId: '1028683149003',
    projectId: 'schedula-6bd5d',
    databaseURL:
        'https://schedula-6bd5d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'schedula-6bd5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC91GDBemLbaivXxAhkbG_SEVphedMeg_o',
    appId: '1:1028683149003:ios:04d8f29c1327a52d0bb54e',
    messagingSenderId: '1028683149003',
    projectId: 'schedula-6bd5d',
    databaseURL:
        'https://schedula-6bd5d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'schedula-6bd5d.appspot.com',
    iosBundleId: 'com.example.schedula',
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1iyMsvi5x1ReLpDoA5AJ98BdkVd6bHvA',
    appId: '1:1028683149003:web:b1d9cc99ba44796d0bb54e',
    messagingSenderId: '1028683149003',
    projectId: 'schedula-6bd5d',
    authDomain: 'schedula-6bd5d.firebaseapp.com',
    databaseURL:
        'https://schedula-6bd5d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'schedula-6bd5d.appspot.com',
    measurementId: 'G-ZWLPVTH079',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1iyMsvi5x1ReLpDoA5AJ98BdkVd6bHvA',
    appId: '1:1028683149003:web:a6377639f50c58f30bb54e',
    messagingSenderId: '1028683149003',
    projectId: 'schedula-6bd5d',
    authDomain: 'schedula-6bd5d.firebaseapp.com',
    databaseURL:
        'https://schedula-6bd5d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'schedula-6bd5d.appspot.com',
    measurementId: 'G-RCKP6S7C4K',
  );
}
